# Generated by Django 5.1.1 on 2024-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carimbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='login',
            field=models.CharField(default='null', max_length=100, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_login',
            field=models.CharField(default='null', max_length=100, verbose_name='Senha'),
        ),
    ]
